# Generated by Django 5.2.6 on 2025-09-25 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('shot', 'Shot'), ('pass', 'Pass'), ('turnover', 'Turnover')], max_length=10)),
                ('action_type', models.CharField(max_length=50)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('is_shooting_foul', models.BooleanField(blank=True, null=True)),
                ('shot_loc_x', models.FloatField(blank=True, null=True)),
                ('shot_loc_y', models.FloatField(blank=True, null=True)),
                ('is_pass_completed', models.BooleanField(blank=True, null=True)),
                ('is_potential_assist', models.BooleanField(blank=True, null=True)),
                ('pass_start_loc_x', models.FloatField(blank=True, null=True)),
                ('pass_start_loc_y', models.FloatField(blank=True, null=True)),
                ('pass_end_loc_x', models.FloatField(blank=True, null=True)),
                ('pass_end_loc_y', models.FloatField(blank=True, null=True)),
                ('turnover_loc_x', models.FloatField(blank=True, null=True)),
                ('turnover_loc_y', models.FloatField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='app.team'),
        ),
    ]
